name: onepref
description: This package is a well-structured wrapper around Flutter’s in_app_purchase API that centralizes in-app purchase (IAP) logic for both Android (Google Play) and iOS (App Store).
version: 0.0.24
homepage: https://github.com/wdtheprovider/onepref

environment:
  sdk: "^3.5.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  in_app_purchase_android: ^0.4.0+6
  in_app_purchase_platform_interface: ^1.4.0
  in_app_purchase_storekit: ^0.4.6
  in_app_purchase: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# The following section is specific to Flutter packages.
flutter:

platforms:
  android:
  ios:
  macos: