name: onepref
description: This package is a well-structured wrapper around Flutter's in_app_purchase API that centralizes in-app purchase (IAP) logic for both Android (Google Play) and iOS (App Store).
version: 0.0.25
homepage: https://github.com/wdtheprovider/onepref

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.5
  in_app_purchase_android: 0.5.0
  in_app_purchase_platform_interface: ^1.4.1
  in_app_purchase_storekit: ^0.4.11
  in_app_purchase: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# The following section is specific to Flutter packages.
flutter:

platforms:
  android:
  ios:
  macos: